[workspace]
members = [
    "halo2",
    "halo2_proofs",
]

[patch.'https://github.com/lanbones/ec-gpu']
ec-gpu-gen = { path = '../ec-gpu/ec-gpu-gen' }

[patch.'crates-io']
rust-gpu-tools={path='../moore/rust-gpu-tools'}